<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-MultiservicioB-2a301d04-6f07-4b2a-9b9c-3afbf952f69c</UserSecretsId>
    <NoWarn>$(NoWarn);NU1901</NoWarn>
    <DefaultItemExcludes>$(DefaultItemExcludes);.buildcheck\**;.objcheck\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\AlertasYnotificaciones\**" />
    <Compile Remove="Views\ConfiguracionGeneral\**" />
    <Compile Remove="Views\EncuestasYcalidad\**" />
    <Compile Remove="Views\EvidenciasYdocumentos\**" />
    <Compile Remove="Views\Geolocalizacion\**" />
    <Compile Remove="NewFolder\**" />
    <Compile Remove="Views\OrdenesServicio\**" />
    <Compile Remove="Views\ReportesEindicadores\**" />
    <Content Remove="Views\AlertasYnotificaciones\**" />
    <Content Remove="Views\ConfiguracionGeneral\**" />
    <Content Remove="Views\EncuestasYcalidad\**" />
    <Content Remove="Views\EvidenciasYdocumentos\**" />
    <Content Remove="Views\Geolocalizacion\**" />
    <Content Remove="NewFolder\**" />
    <Content Remove="Views\OrdenesServicio\**" />
    <Content Remove="Views\ReportesEindicadores\**" />
    <EmbeddedResource Remove="Views\AlertasYnotificaciones\**" />
    <EmbeddedResource Remove="Views\ConfiguracionGeneral\**" />
    <EmbeddedResource Remove="Views\EncuestasYcalidad\**" />
    <EmbeddedResource Remove="Views\EvidenciasYdocumentos\**" />
    <EmbeddedResource Remove="Views\Geolocalizacion\**" />
    <EmbeddedResource Remove="NewFolder\**" />
    <EmbeddedResource Remove="Views\OrdenesServicio\**" />
    <EmbeddedResource Remove="Views\ReportesEindicadores\**" />
    <None Remove="Views\AlertasYnotificaciones\**" />
    <None Remove="Views\ConfiguracionGeneral\**" />
    <None Remove="Views\EncuestasYcalidad\**" />
    <None Remove="Views\EvidenciasYdocumentos\**" />
    <None Remove="Views\Geolocalizacion\**" />
    <None Include="NewFolder\**" />
    <None Remove="Views\OrdenesServicio\**" />
    <None Remove="Views\ReportesEindicadores\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
  </ItemGroup>

</Project>
